#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

set -x
set -e
source "${SCRIPT_DIR}/_set_env.sh"

export PYTHONPATH="${PY_BUILD_DIR}"
export PATH="${VENV_BIN}:${PATH}"
exec $*
